version: '3.3'
services:
  db:
      image: "mcr.microsoft.com/mssql/server"
      ports:
        - "1433:1433"
      volumes:
        - ./data/db:/var/opt/mssql/data
        - ./data/log:/var/opt/mssql/log

      environment:
          SA_PASSWORD: "sajadsajad1"
          ACCEPT_EULA: "Y"

  redis:
      image: "redis:alpine" 
      hostname: redis
      ports:
        - '6379:6379'
      volumes: 
        - ./data/redis:/var/lib/redis
        - ./data/redis/config:/usr/local/etc/redis/redis.conf
        - ./data/redis:/usr/local/etc/redis/
      # links:
      #   - redis-commander

  # redis-commander:
  #     image: rediscommander/redis-commander:latest
  #     restart: always
  #     environment:
  #       - REDIS_HOSTS=local:redis:6379
  #     ports:
  #       - 8081:8081