version: '3.3'
services:
  db:
      image: "mcr.microsoft.com/mssql/server"
      ports:
        - "1433:1433"
      volumes:
        - ./data/db:/var/opt/mssql/data
        - ./data/log:/var/opt/mssql/log

      environment:
          SA_PASSWORD: "sajadsajad1"
          ACCEPT_EULA: "Y"
